### ISSUE TITLE
Can't show Panel, 

### ISSUE THREAD

**Issue by lordnegre** [TuyaInc/tuyasmart_camera_panel_ios_sdk#1]
We are integrating this SDK but when we try to show the panel in order to show the camera on 'sp' device, we have this output.

SDK: iOS 13
Xcode: 11

TuyaCameraSDK Ver:3.15.0, Built-at: Apr 10 2020 14:40:41
tuya p2p rtc sdk version: 0xf403020e, Apr 10 2020 11:58:20
TuyaCameraSDK: [INFO] P2pModuleV2 initialized.
tymedia ty_media_init 
tymedia create initialized_ 0 
AudioProcessing initialize success 
tymedia audio_recorder enter 
tymedia audio_renderer enter 
41362934 [32mINFO [0m [90msrc/tuya_rtc.c:5143:[0m try connect to bf1be5a60b9ad9800f8cy0, token len = 621
41362934 [31mERROR[0m [90msrc/tuya_rtc.c:5115:[0m connect failed: invalid token
2020-06-16 08:34:40.288522+0200  camera occurred error: -5, step: 1, device: Pet feeder-bf1be5a60b9ad9800f8cy0
2020-06-16 08:34:40.321950+0200  Metal GPU Frame Capture Enabled
2020-06-16 08:34:40.322096+0200  Metal API Validation Enabled

We are using the documentation and this is the resulting view

![panel](https://user-images.githubusercontent.com/10495752/85116406-9150aa80-b21d-11ea-8126-294a2a59a5a6.png)

**Comment by jmartinesp** [comment]
If it helps, we tried using the example project provided with our app credentials and the same error happened. However, its Android counterpart works just fine.

**Comment by alongLFB** [comment]
could you please provide the podfile.lock? so that i could check the depend SDK tag version.

**Comment by jmartinesp** [comment]
Sure: https://gist.github.com/Arasthel/d4943b310f51daa2dfc586a2c4d480da

This is the Podfile.lock of the Example project in this repository. We tested it in the Example project too to make sure we weren't doing anything wrong. The results are the same as the one @pabloviciano published in his first message for the app we're developing, a `connect failed: invalid token` error and no camera preview.

**Comment by alongLFB** [comment]
you can see this changelog: https://tuyainc.github.io/tuyasmart_camera_ios_sdk_doc/en/resource/version_record.html . this 
current panelSDK depend on 3.15.0 (2020-02-21). you could write these tags in you podfile file. or you could use camera_panel_biz_bundle : https://tuyainc.github.io/tuyasmart_bizbundle_ios_doc/en/pages/ipc_panel/
![image](https://user-images.githubusercontent.com/17883682/86218598-9ca7bc80-bbb3-11ea-9a4d-77bfd87d4fce.png)

**Comment by jmartinesp** [comment]
Thank you so much for your help. We were able to get it working both on the CameraPanelBizBundle and the current CameraPanelSDK using those exact versions. 

However, we're unsure whether you'd recommend using the BizBundles or the current SDKs since we're not sure if those BizBundles are production ready - CocoaPods warns that some dependencies don't have a stable version yet. Could you give us some advice? Is CameraPanelSDK going to be deprecated soon, should we use the CameraPanelBizBundle instead?

**Comment by alongLFB** [comment]
yes，the CameraPanelSDK is deprecated， and we suggest that you'd better use the CameraPanelBizBundle instead. we will supplemental migration documentation soon。
